name: AppPerf
root: .
windows:
  - runner:
      layout: even-vertical
      panes:
        - bin/rails server -p 5000
        - bundle exec sidekiq --queue app_perf --verbose
        - sleep 10 && bundle exec app_perf_agent --license 30b5805c-25d8-4fcd-875e-4fd9be32993e --host localhost:5000
